In [1]:
import os, sys
sys.path.append('..')
from os.path import abspath, dirname
import zarr
import z5py
import numpy as np
import pandas as pd
from glob import glob 
from skimage.measure import regionprops
from skimage.io import imread, imsave
from scipy import stats
from scipy.stats import skewnorm, lognorm
from scipy.optimize import minimize
import itertools

from easi_fish import n5_metadata_utils as n5mu
from easi_fish import roi_prop, spot, intensity
import warnings
warnings.filterwarnings('ignore')

import importlib
importlib.reload(spot)
importlib.reload(roi_prop)
importlib.reload(intensity)

"""
Spot counts for cells with highly expressed genes (dense spots)
1. Measure total intensity of every ROI after bleed-through correction and background subtraction.
2. Calculate the number of spot from total intensity based on unit-spot intensity
3. Correlate the number of spots (from air-localize) with the total fluorescence intensity/voxel in each ROI and determine a 'cutoff'. 
   Spot count > cutoff: use spot count converted based on total fluorescence intensity; 
   Spot count < cutoff: use spot count from Airlocalize
"""

"\nSpot counts for cells with highly expressed genes (dense spots)\n1. Measure total intensity of every ROI after bleed-through correction and background subtraction.\n2. Calculate the number of spot from total intensity based on unit-spot intensity\n3. Correlate the number of spots (from air-localize) with the total fluorescence intensity/voxel in each ROI and determine a 'cutoff'. \n   Spot count > cutoff: use spot count converted based on total fluorescence intensity; \n   Spot count < cutoff: use spot count from Airlocalize\n"

In [2]:
def get_unit_spot_intn(path_spot):
    """estimate unit spot intensity
    """
    spot = np.loadtxt(path_spot, delimiter=',')
    # (x, y, z, I)
    vox=[0.92,0.92,0.84]
    spot[:,:3]=spot[:,:3]/vox  # convert from physical unit to pixel unit
    ##remove spots on edges (eliminate false detection)
    spot = spot[np.logical_and(spot[:,0]<=1500, spot[:,0]>250)]
    spot = spot[np.logical_and(spot[:,1]<=1500, spot[:,1]>250)]
    spot = spot[np.logical_and(spot[:,2]<=650,  spot[:,2]>150)]   
    
    ## assign the most frequent intensity as the single-spot-intensity
    spot_int = spot[:,3]
    spot_int = spot_int[spot_int!=-8.0] # ???
    n,b=np.histogram(spot_int, bins=5000)
    unit_intn = b[np.argmax(n)]
    
    return unit_intn

def get_spot_counts_from_intn(path_intn, path_spot, roi_meta):
    """estimate spot_counts from cell_intensities; estimate unit-spot intensity first
    """
    unit_intn = get_unit_spot_intn(path_spot) # get unit intn
    
    cell_int = pd.read_csv(path_intn, sep=',', index_col=0)
    cell_int = cell_int.reindex(roi_meta.index) ## only include intact ROIs###

    vec_mean = cell_int['mean_intensity'].values
    vec_area = roi_meta['area'].values

    # background
    n,b = np.histogram(vec_mean, bins=1000)
    bg = b[np.argmax(n)]    
    
    # count
    vec_count = np.clip(vec_mean - bg, 0, None)*vec_area/unit_intn
    return vec_count

In [3]:
## input
# input_dir = "D:\\SWAP\\Vincent\\lt171_FlpO\\gene_new_4tile\\outputs"
input_dir = "D:\\SWAP\\Vincent\\lt172_exps\\gene\\outputs"
bleed_thru_epsilon = 1
output_dir = os.path.join(input_dir, f"test-oct6_epsilon{bleed_thru_epsilon}")  

# fixed image (directory - n5 format)
# fix_dir = os.path.join(input_dir, "r2\\export_sigma3.n5")
fix_dir = os.path.join(input_dir, "lt172_gene_r3\\export.n5")
# get appropriate image data within fix_dir
subpath='\\c3\\s2' # what does the subpath mean?

# segmentation mask (tif format accepted here)
lb_dir  = os.path.join(input_dir, "lt172_gene_r3\\segmentation\\lt172_gene_r3-c3.tif" ) 

# registered image (directory - n5 format)
# reg_dir = os.path.join(input_dir, "lt172_gene_r1\\registration\\lt171_gene_4tile_r1-to-lt171_gene_4tile_r2\\warped")  
reg_dirs = [
    os.path.join(input_dir, "lt172_gene_r1\\registration\lt172_gene_r1-to-lt172_gene_r3\\warped"),
    os.path.join(input_dir, "lt172_gene_r4\\registration\lt172_gene_r4-to-lt172_gene_r3\\warped"),
    os.path.join(input_dir, "lt172_gene_r5\\registration\lt172_gene_r5-to-lt172_gene_r3\\warped"),
]

# spot dir 
spot_dir = os.path.join(input_dir, "spots_pooled") # pool spots together; warpped and fixed
intn_dir = os.path.join(input_dir, "intensities_pooled") # pool spots together; warpped and fixed
# for every gene
rounds = ['r1', 'r3', 'r4', 'r5']
channels = ['c0', 'c1', 'c2', 'c4']
# r1 should be the wrappped one
fx_spots = [os.path.join(spot_dir, f'spots_{r}_{c}.txt') 
                 for r, c in itertools.product(rounds, channels)]
fx_intns = [os.path.join(intn_dir, f'{r}_{c}_intensity.csv') 
                 for r, c in itertools.product(rounds, channels)]

for f in fx_spots:
    assert os.path.isfile(f)
for f in fx_intns:
    assert os.path.isfile(f)

## output
# out_mask = os.path.join(output_dir, 'mask.tif')
out_badroi = os.path.join(output_dir, 'bad_roi_list.npy')
out_allroi = os.path.join(output_dir, "roi_all.csv") 
out_roi = os.path.join(output_dir, "roi.csv") 
out_spots = os.path.join(output_dir, "spotcount.csv")
out_spots_intn = os.path.join(output_dir, "spotcount_intn.csv")
# out_intensity = os.path.join(output_dir, "intensity_c0_r2.csv")
out_spots_merged = os.path.join(output_dir, 'spotcount_merged.csv')

In [4]:
%%time
# output dir
if not os.path.isdir(output_dir):
    print(output_dir)
    os.mkdir(output_dir)
    
#voxel size in Âµm (x, y, z) (post-expansion)
vox= n5mu.read_voxel_spacing(fix_dir, subpath)
#image size in pixel (x, y, z)
grid=n5mu.read_voxel_grid(fix_dir, subpath)
#image size in physical space (x, y, z) (post-expansion)
size=grid*vox
print('voxel size is:',vox)
print('image size in pixel unit is:',grid)
print('image size in um unit is:',size)

# get appropriate image data
print("loading images...")
# fix = zarr.open(store=zarr.N5Store(fix_dir), mode='r')     
# img1 = fix[subpath][:, :, :]

lb=imread(lb_dir)
print(lb.shape)
roi = np.max(lb)
print(roi)

mask=np.full((grid[2], grid[1], grid[0]),1)
for reg_dir in reg_dirs:
    reg = zarr.open(store=zarr.N5Store(reg_dir), mode='r')     
    img2 = reg[subpath][:, :, :]
    print("image loaded")
    mask[img2==0]=0
    
# imsave(out_mask, mask)
print("mask generated")
print("mask dimension is:", mask.shape)

# # Get list of ROIs that are fully or partially outside the mask 
### Make sure to only include ROIs that are intact and in the overlapping regions across all rounds of FISH
bad_roi=np.unique(lb[mask==0])
if bad_roi[0] == 0:
    bad_roi = bad_roi[1:]
np.save(out_badroi, bad_roi)
print("# of ROIs rejected:", len(bad_roi))

D:\SWAP\Vincent\lt172_exps\gene\outputs\test-oct6_epsilon1
voxel size is: [0.92 0.92 0.84]
image size in pixel unit is: [915 909 895]
image size in um unit is: [841.8  836.28 751.8 ]
loading images...
(895, 909, 915)
10042
image loaded
image loaded
image loaded
mask generated
mask dimension is: (895, 909, 915)
# of ROIs rejected: 319
CPU times: total: 43.4 s
Wall time: 27.2 s

In [5]:
%%time
roi_meta_all = roi_prop.roi_prop_v2(lb)
roi_meta_all.to_csv(out_allroi)

roi_meta = roi_meta_all.set_index('roi').copy()
roi_meta = roi_meta.loc[roi_meta.index.difference(bad_roi)]
roi_meta.to_csv(out_roi)

CPU times: total: 13.4 s
Wall time: 13.4 s

In [6]:
# remove bleed through!
spots_bld_thru_removed = {}
c_qry = 'c0'
c_ref = 'c4'
for r in rounds:
    f_ref = os.path.join(spot_dir, f'spots_{r}_{c_ref}.txt')
    f_qry = os.path.join(spot_dir, f'spots_{r}_{c_qry}.txt')
    f_qry_removed = os.path.join(spot_dir, f'removed_spots_{r}_{c_qry}.txt')
    
    ref_dots = np.loadtxt(f_ref, delimiter=',')
    qry_dots = np.loadtxt(f_qry, delimiter=',')
    qry_kept, qry_removed = spot.remove_bleed_thru_spots(ref_dots, qry_dots, epsilon=bleed_thru_epsilon)
    
    # keep kept 
    spots_bld_thru_removed[f"{r}_{c_qry}"] = qry_kept
    # save removed
    np.savetxt(f_qry_removed, qry_removed, delimiter=",")

5344/75147 = 7.1% removed
1727/288677 = 0.6% removed
6232/470737 = 1.3% removed
1906/225101 = 0.8% removed

In [7]:
%%time
# count spots
lb_id = np.unique(lb[lb!=0]) # exclude 0
lb_id = np.hstack([[0], lb_id]) # include 0
spotcount = pd.DataFrame(index=lb_id)
for i, (r, c) in enumerate(itertools.product(rounds, channels)):
    if f"{r}_{c}" in spots_bld_thru_removed.keys():
        print(f"{r}_{c}: load from bleed_thru_corrected spots")
        spots_rc = spots_bld_thru_removed[f"{r}_{c}"]
    else:
        f_spots = fx_spots[i]
        print(f"{r}_{c}: load from {f_spots}")
        spots_rc = np.loadtxt(f_spots, delimiter=',')
        
    res = spot.spot_counts_worker(lb, spots_rc, lb_id=lb_id, 
                             remove_emptymask=True, 
                             verbose=True,
                             )
    spotcount[f"{r}_{c}"] = res 
spotcount = spotcount.iloc[1:] # remove 0
spotcount.to_csv(out_spots)
spotcount

r1_c0: load from bleed_thru_corrected spots
removed 0 due to nan
69,709/69,803 spots in range (915, 909, 895)
r1_c1: load from D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r1_c1.txt
removed 4 due to nan
385,561/386,171 spots in range (915, 909, 895)
r1_c2: load from D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r1_c2.txt
removed 0 due to nan
46,159/46,507 spots in range (915, 909, 895)
r1_c4: load from D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r1_c4.txt
removed 0 due to nan
14,997/15,080 spots in range (915, 909, 895)
r3_c0: load from bleed_thru_corrected spots
removed 0 due to nan
286,949/286,950 spots in range (915, 909, 895)
r3_c1: load from D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r3_c1.txt
removed 0 due to nan
451,189/451,190 spots in range (915, 909, 895)
r3_c2: load from D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r3_c2.txt
removed 0 due to nan
101,224/101,227 spots in range (915, 909, 895)
r3_c4: load from D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r3_c4.txt
removed 0 due to nan
29,700/29,701 spots in range (915, 909, 895)
r4_c0: load from bleed_thru_corrected spots
removed 16 due to nan
463,753/464,505 spots in range (915, 909, 895)
r4_c1: load from D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r4_c1.txt
removed 5 due to nan
334,082/335,074 spots in range (915, 909, 895)
r4_c2: load from D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r4_c2.txt
removed 30 due to nan
1,578,795/1,581,403 spots in range (915, 909, 895)
r4_c4: load from D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r4_c4.txt
removed 6 due to nan
45,553/45,893 spots in range (915, 909, 895)
r5_c0: load from bleed_thru_corrected spots
removed 2 due to nan
222,506/223,195 spots in range (915, 909, 895)
r5_c1: load from D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r5_c1.txt
removed 1 due to nan
122,907/123,878 spots in range (915, 909, 895)
r5_c2: load from D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r5_c2.txt
removed 4 due to nan
179,732/180,911 spots in range (915, 909, 895)
r5_c4: load from D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r5_c4.txt
removed 0 due to nan
11,248/11,472 spots in range (915, 909, 895)
CPU times: total: 27 s
Wall time: 27 s

,r1_c0,r1_c1,r1_c2,r1_c4,r3_c0,r3_c1,r3_c2,r3_c4,r4_c0,r4_c1,r4_c2,r4_c4,r5_c0,r5_c1,r5_c2,r5_c4
1,30.0,75.0,0.0,0.0,51.0,97.0,7.0,3.0,22.0,215.0,280.0,4.0,8.0,11.0,30.0,0.0
2,4.0,35.0,2.0,2.0,20.0,102.0,4.0,4.0,20.0,30.0,219.0,2.0,2.0,13.0,8.0,0.0
3,8.0,49.0,0.0,8.0,14.0,143.0,4.0,13.0,22.0,12.0,314.0,9.0,22.0,39.0,6.0,0.0
4,34.0,50.0,3.0,0.0,22.0,99.0,5.0,6.0,8.0,381.0,354.0,4.0,13.0,25.0,34.0,0.0
5,9.0,28.0,1.0,2.0,37.0,76.0,5.0,4.0,22.0,11.0,167.0,7.0,3.0,12.0,7.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10038,0.0,0.0,0.0,0.0,4.0,2.0,0.0,0.0,2.0,0.0,8.0,1.0,1.0,1.0,0.0,0.0
10039,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,1.0,0.0,1.0,1.0,0.0,0.0,2.0,1.0
10040,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0
10041,3.0,23.0,3.0,0.0,3.0,10.0,3.0,0.0,0.0,1.0,0.0,0.0,1.0,15.0,1.0,1.0
10042,0.0,1.0,0.0,0.0,2.0,3.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0

In [8]:
# spot count calculated from total fluorescence intensity
spotcount_intn = pd.DataFrame(index=roi_meta.index, dtype=float)
for i, (r, c) in enumerate(itertools.product(rounds, channels)):
    f_spots = fx_spots[i]
    f_intns = fx_intns[i]
    print(r, c, f_spots, f_intns)
    
    vec_count = get_spot_counts_from_intn(f_intns, f_spots, roi_meta)
    spotcount_intn[f'{r}_{c}'] = vec_count
spotcount_intn.to_csv(out_spots_intn)
spotcount_intn

r1 c0 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r1_c0.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r1_c0_intensity.csv
r1 c1 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r1_c1.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r1_c1_intensity.csv
r1 c2 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r1_c2.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r1_c2_intensity.csv
r1 c4 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r1_c4.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r1_c4_intensity.csv
r3 c0 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r3_c0.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r3_c0_intensity.csv
r3 c1 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r3_c1.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r3_c1_intensity.csv
r3 c2 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r3_c2.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r3_c2_intensity.csv
r3 c4 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r3_c4.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r3_c4_intensity.csv
r4 c0 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r4_c0.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r4_c0_intensity.csv
r4 c1 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r4_c1.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r4_c1_intensity.csv
r4 c2 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r4_c2.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r4_c2_intensity.csv
r4 c4 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r4_c4.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r4_c4_intensity.csv
r5 c0 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r5_c0.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r5_c0_intensity.csv
r5 c1 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r5_c1.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r5_c1_intensity.csv
r5 c2 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r5_c2.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r5_c2_intensity.csv
r5 c4 D:\SWAP\Vincent\lt172_exps\gene\outputs\spots_pooled\spots_r5_c4.txt D:\SWAP\Vincent\lt172_exps\gene\outputs\intensities_pooled\r5_c4_intensity.csv

,r1_c0,r1_c1,r1_c2,r1_c4,r3_c0,r3_c1,r3_c2,r3_c4,r4_c0,r4_c1,r4_c2,r4_c4,r5_c0,r5_c1,r5_c2,r5_c4
roi,,,,,,,,,,,,,,,,
1,28.499053,23.936460,6.139836,8.734649,21.648991,44.394367,7.039668,6.686004,13.039503,182.850337,196.724486,5.987592,3.649613,0.000000,33.820334,4.197480
2,4.438307,0.000000,0.000000,3.314127,0.000000,31.578833,7.246729,8.121454,6.732301,20.128761,129.460483,6.138109,1.864689,4.789944,6.760476,20.176098
3,0.000000,3.822017,0.000000,0.000000,0.000000,72.546163,0.000000,0.462717,0.000000,5.421599,166.050006,0.000000,0.000000,21.594256,0.000000,0.000000
4,15.982473,18.839709,0.000000,0.709593,0.000000,23.388870,0.000000,1.623833,0.000000,370.657448,186.104555,0.000000,0.000000,3.207030,23.611026,11.661198
5,4.018570,0.000000,0.000000,2.799577,0.000000,21.804443,5.060271,3.561327,13.845422,0.000000,104.323914,7.635368,0.000000,2.798803,0.589812,8.894599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10038,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.003488,0.585929,0.444537,4.864178,0.176567,0.000000,1.000142,0.000000,0.000000
10039,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10040,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.169383,0.000000,0.000000,0.000000,0.160700,0.000000,0.000000
10041,16.145138,32.826946,27.038811,0.164397,4.376671,14.328491,9.299357,2.367209,0.527930,11.998407,4.361051,2.493651,8.468575,24.779259,10.890301,6.008139
10042,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.597649,2.279334,0.000000,0.000000,0.000000,0.074756,0.000000

In [9]:
# update spotcount using df_count
spotcount_sub = spotcount.reindex(roi_meta.index)
volumes = (roi_meta['area']*2*2*2/(0.92*0.92*0.84)) # convert um^3 to voxel values
density = spotcount_sub.divide(volumes, axis=0)
cond = density <= 0.01  ##this threshold corresponds to spot-spot distance ~1.3 um apart
print((~cond).sum())
spotcount_merged = spotcount_sub.where(cond, spotcount_intn)  
spotcount_merged.to_csv(out_spots_merged)
spotcount_merged

r1_c0       0
r1_c1      23
r1_c2       0
r1_c4       0
r3_c0       0
r3_c1      81
r3_c2       3
r3_c4       0
r4_c0     264
r4_c1     454
r4_c2    5396
r4_c4       0
r5_c0       0
r5_c1       3
r5_c2       0
r5_c4       0
dtype: int64

,r1_c0,r1_c1,r1_c2,r1_c4,r3_c0,r3_c1,r3_c2,r3_c4,r4_c0,r4_c1,r4_c2,r4_c4,r5_c0,r5_c1,r5_c2,r5_c4
roi,,,,,,,,,,,,,,,,
1,30.0,75.0,0.0,0.0,51.0,97.0,7.0,3.0,22.0,182.850337,196.724486,4.0,8.0,11.0,30.0,0.0
2,4.0,35.0,2.0,2.0,20.0,102.0,4.0,4.0,20.0,30.000000,129.460483,2.0,2.0,13.0,8.0,0.0
3,8.0,49.0,0.0,8.0,14.0,143.0,4.0,13.0,22.0,12.000000,166.050006,9.0,22.0,39.0,6.0,0.0
4,34.0,50.0,3.0,0.0,22.0,99.0,5.0,6.0,8.0,370.657448,186.104555,4.0,13.0,25.0,34.0,0.0
5,9.0,28.0,1.0,2.0,37.0,76.0,5.0,4.0,22.0,11.000000,104.323914,7.0,3.0,12.0,7.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10038,0.0,0.0,0.0,0.0,4.0,2.0,0.0,0.0,2.0,0.000000,8.000000,1.0,1.0,1.0,0.0,0.0
10039,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,1.0,0.000000,1.000000,1.0,0.0,0.0,2.0,1.0
10040,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.000000,0.000000,0.0,0.0,2.0,0.0,0.0
10041,3.0,23.0,3.0,0.0,3.0,10.0,3.0,0.0,0.0,1.000000,0.000000,0.0,1.0,15.0,1.0,1.0
10042,0.0,1.0,0.0,0.0,2.0,3.0,0.0,0.0,1.0,1.000000,0.000000,0.0,0.0,2.0,0.0,0.0